FROM openjdk:8-jdk-alpine

ARG ARTIFACT_NAME="minha-grana-api"
ARG ARTIFACT_VERSION="0.0.1-SNAPSHOT"
ARG APPLICATION_JAR="$ARTIFACT_NAME-$ARTIFACT_VERSION.jar"
ENV APPLICATION_PATH=/app/$APPLICATION_JAR

WORKDIR /app
COPY ./target/$APPLICATION_JAR /app/$APPLICATION_JAR

ENTRYPOINT [ "sh", "-c", "java -jar $APPLICATION_PATH" ]
